add_newline = false
command_timeout = 1000
palette = "gruvbox_light_hard"
format = "$hostname${custom.jj}$directory $character"

[character]
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"
vicmd_symbol = "[N](mauve) [➜](green)"

[directory]
style = "blue"
truncation_length = 4
truncate_to_repo = true

[git_branch]
disabled = true

[git_status]
disabled = true

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "green bold"

[palettes.gruvbox_light_hard]
rosewater = "#af3a03"
flamingo = "#9d0006"
pink = "#b16286"
mauve = "#8f3f71"
red = "#cc241d"
maroon = "#9d0006"
peach = "#d65d0e"
yellow = "#d79921"
green = "#98971a"
teal = "#689d6a"
sky = "#458588"
sapphire = "#076678"
blue = "#076678"
lavender = "#b16286"
text = "#282828"
subtext1 = "#3c3836"
subtext0 = "#504945"
overlay2 = "#665c54"
overlay1 = "#7c6f64"
overlay0 = "#928374"
surface2 = "#a89984"
surface1 = "#bdae93"
surface0 = "#d5c4a1"
base = "#f9f5d7"
mantle = "#fbf1c7"
crust = "#f2e5bc"
