add_newline = false
command_timeout = 1000
palette = "coffee"
format = "$hostname${custom.jj}$directory $character"

[character]
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"
vicmd_symbol = "[N](mauve) [➜](green)"

[directory]
style = "lavender"
truncation_length = 4
truncate_to_repo = true

[git_branch]
disabled = true

[git_status]
disabled = true

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "green bold"

[palettes.coffee]
rosewater = "#f5deb3"
flamingo = "#c1deff"
pink = "#ca30c7"
mauve = "#6871ff"
red = "#c91b00"
maroon = "#ff6e67"
peach = "#adaa00"
yellow = "#b2af1b"
green = "#00c200"
teal = "#00b8ba"
sky = "#20bdbf"
sapphire = "#0225c7"
blue = "#0225c7"
lavender = "#6871ff"
text = "#000000"
