add_newline = false
command_timeout = 1000
palette = "gruvbox_light"
format = "$hostname${custom.jj}$directory $character"

[character]
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"
vicmd_symbol = "[N](purple) [➜](green)"

[directory]
style = "blue"
truncation_length = 4
truncate_to_repo = true

[git_branch]
disabled = true

[git_status]
disabled = true

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "green bold"

[palettes.gruvbox_light]
bg = "#fbf1c7"
bg1 = "#ebdbb2"
bg2 = "#d5c4a1"
bg3 = "#bdae93"
bg4 = "#a89984"
fg = "#3c3836"
fg1 = "#3c3836"
fg2 = "#504945"
fg3 = "#665c54"
fg4 = "#7c6f64"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
purple = "#b16286"
aqua = "#689d6a"
orange = "#d65d0e"
bright_red = "#9d0006"
bright_green = "#79740e"
bright_yellow = "#b57614"
bright_blue = "#076678"
bright_purple = "#8f3f71"
bright_aqua = "#427b58"
bright_orange = "#af3a03"
gray = "#928374"
